### PR TITLE
handler/tianmu_handler: fix handler api by MySQL8

### PR DESCRIPTION
**Pull request by DandreChen**
bas_ext() is deleted
	get_row_type() is deleted
	index_type() is deleted
	cond_pop() is deleted
	explain_message() is deleted
	register_query_cache_table() is deleted

### CODE REVIEW

**Comment by DandreChen** [comment]
#63

**Comment by DandreChen** [comment]
#63

**Comment by DandreChen** [comment]
#64

**Review by andyli029 — APPROVED** [review]
LGTM.

**Pull request merged**
